
INSERT INTO `products` (`id`, `category`, `brand`, `name`, `size`, `price`, `imagePath`, `description`) VALUES
(1, 'men', 'Puma', 'Cotton Polyester Blue Shirt', 'L', '1500', '34.jpg', 'description'),
(2, 'men', 'Nike', 'Puma WhiteTshirt', 'L', '2000', '78.jpg', 'description'),
(3, 'men', 'Puma', 'Puma Black Jacket', 'L', '100', '33.jpg', 'description'),
(4, 'men', 'Puma', 'Puma Black Blue Tshirt', 'L', '2000', '56.jpg', 'description'),
(5, 'men', 'Addidas', 'Skye Blue Tshirt', 'L', '800', '333.jpg', 'description'),
(6, 'men', 'Puma', 'Blue Jeans Shirt', 'L', '1000', '777.jpg', 'description'),
(7, 'woman', 'Nike', 'Blue Long Sleeves Tshirt', 'L', '1000', '000.jpg', 'description'),
(8, 'woman', 'HRX', 'Blue Long Sleeves Tshirt', 'L', '1200', '00.jpg', 'description'),
(9, 'woman', 'Puma', 'Black Long Sleeves Tshirt', 'L', '1000', '4.jpg', 'description'),
(10, 'woman', 'Puma', 'Umbrella Full Dress', 'L', '1500', '6.jpg', 'description'),
(11, 'woman', 'Addidas', 'Red Umbrella Full Dress', 'L', '2000', '11.jpg', 'description'),
(12, 'woman', 'Puma', 'Red Party Dress', 'L', '3000', '44.jpg', 'description'),
(13, 'woman', 'Addidas', 'White Addidas Tshirt', 'L', '1200', '77.jpg', 'description'),
(14, 'woman', 'Addidas', 'Black Addidas Tshirt', 'L', '1200', '88.jpg', 'description'),
(15, 'woman', 'Puma', 'Blue Addidas Tshirt', 'L', '2000', '888.jpg', 'description'),
(16, 'kids', 'Nike', 'White T-shirt', 'S', '900', '0009.jpg', 'description'),
(17, 'kids', 'HRX', 'Black T-shirt', 'S', '1900', '2123.jpg', 'description'),
(18, 'kids', 'Puma', 'White Half Sleeve T-shirt', 'S', '900', '22133.jpg', 'description'),
(19, 'kids', 'Puma', 'Red T-shirt', 'S', '1900', '66676.jpg', 'description'),
(20, 'kids', 'Addidas', 'BlackT-shirt', 'S', '800', '768678.jpg', 'description'),
(21, 'kids', 'Puma', 'Yellow T-shirt', 'S', '2000', '23423.jpg', 'description'),
(22, 'electronics', 'Boat', 'Boat Headphones', '5', '2000', 'b.jpg', 'description'),
(23, 'electronics', 'JBL', 'High Bass Headphones', '5', '2000', 'bb.jpg', 'description'),
(24, 'electronics', 'NOISE', 'boat Headphones', '5', '3000', 'download.jpg', 'description'),
(25, 'electronics', 'Boat', 'Boat Bass Headphones', '5', '4500', 'bbb.jpg', 'description'),
(26, 'electronics', 'JBL', 'JBL Headphones', '5', '2000', 'bbbbb.jpg', 'description'),
(27, 'electronics', 'NOISE', 'NOISE Headphones', '5', '2500', 'jjjj.jpg', 'description'),
(28, 'gadgets', 'Realme', 'Realme C20', '5', '6900', 'm.jpeg', 'description'),
(29, 'gadgets', 'Xiami', 'Poco M3', '5', '10,499', 'mm.jpeg', 'description'),
(30, 'gadgets', 'Xiami', 'Poco C3', '5', '7499', 'mmm.jpeg', 'description'),
(31, 'gadgets', 'Apple', 'Apple iPhone 11', '5', '49,999', 'mmmm.jpeg', 'description'),
(32, 'gadgets', 'Realme', 'Realme 8', '5', '13999', 'mmmmm.jpeg', 'description'),
(33, 'gadgets', 'Realme', 'Realme Narzo 30 Pro 5G', '5', '15,499', 'mmmmmm.jpeg', 'description');